/* SPDX-License-Identifier: GPL-2.0-only */
/*
 * Copyright 2024 Alif Semiconductor.
 * Author: Harith George <harith.g@alifsemi.com>
 */

#ifndef __DT_BINDINGS_CLOCK_ENSEMBLE_H
#define __DT_BINDINGS_CLOCK_ENSEMBLE_H

#define ENSEMBLE_DUMMY_CLK			0
#define ENSEMBLE_LFRC_CLK			1
#define ENSEMBLE_LFXO_CLK			2
#define ENSEMBLE_HFRC_CLK			3
#define ENSEMBLE_HFXO_CLK			4
#define ENSEMBLE_S32K_CLK			5
#define ENSEMBLE_PLL_CLK1			6
#define ENSEMBLE_PLL_CLK3			7
#define ENSEMBLE_SYST_ACLK			8
#define ENSEMBLE_SYST_HCLK			9
#define ENSEMBLE_SYST_PCLK			10
#define ENSEMBLE_HFOSC_CLK			11
#define ENSEMBLE_160M_CLK			12
#define ENSEMBLE_160M_SCLK			13
#define ENSEMBLE_USB_SCLK			14
#define ENSEMBLE_USB_CLK			15
#define ENSEMBLE_AUDIO_CLK			16
#define ENSEMBLE_UART0_CLK_SEL			17
#define ENSEMBLE_UART1_CLK_SEL			18
#define ENSEMBLE_UART2_CLK_SEL			19
#define ENSEMBLE_UART3_CLK_SEL			20
#define ENSEMBLE_UART4_CLK_SEL			21
#define ENSEMBLE_UART5_CLK_SEL			22
#define ENSEMBLE_UART6_CLK_SEL			23
#define ENSEMBLE_UART7_CLK_SEL			24
#define ENSEMBLE_UART0_CLK			25
#define ENSEMBLE_UART1_CLK			26
#define ENSEMBLE_UART2_CLK			27
#define ENSEMBLE_UART3_CLK			28
#define ENSEMBLE_UART4_CLK			29
#define ENSEMBLE_UART5_CLK			30
#define ENSEMBLE_UART6_CLK			31
#define ENSEMBLE_UART7_CLK			32
#define ENSEMBLE_CANFD_CLK_SEL			33
#define ENSEMBLE_CANFD_CLK			34
#define ENSEMBLE_I2S0_CLK_SEL			35
#define ENSEMBLE_I2S1_CLK_SEL			36
#define ENSEMBLE_I2S2_CLK_SEL			37
#define ENSEMBLE_I2S3_CLK_SEL			38
#define ENSEMBLE_I2S0_CLK			39
#define ENSEMBLE_I2S1_CLK			40
#define ENSEMBLE_I2S2_CLK			41
#define ENSEMBLE_I2S3_CLK			42
#define ENSEMBLE_I3C_CLK			43
#define ENSEMBLE_ADC24_CLK			44
#define ENSEMBLE_ADC120_CLK			45
#define ENSEMBLE_ADC121_CLK			46
#define ENSEMBLE_ADC122_CLK			47
#define ENSEMBLE_DAC120_CLK			48
#define ENSEMBLE_DAC121_CLK			49
#define ENSEMBLE_CMP0_CLK			50
#define ENSEMBLE_CMP1_CLK			51
#define ENSEMBLE_CMP2_CLK			52
#define ENSEMBLE_CMP3_CLK			53
#define ENSEMBLE_CAMERA_PIXCLK			54
#define ENSEMBLE_CDC200_PIXCLK			55
#define ENSEMBLE_CDC200_DPI_PIXCLK		56
#define ENSEMBLE_CSI_PIXCLK			57
#define ENSEMBLE_MIPI_BYPASS_CLK		58
#define ENSEMBLE_MIPI_PLLREF_CLK		59
#define ENSEMBLE_MIPI_RXDPHY_CLK		60
#define ENSEMBLE_MIPI_TXDPHY_CLK		61

#define ENSEMBLE_CLK_END			129

#endif /* __DT_BINDINGS_CLOCK_ENSEMBLE_H */
