/* SPDX-License-Identifier: GPL-2.0-only */
/*
 * Copyright 2024 Alif Semiconductor.
 * Author: Harith George <harith.g@alifsemi.com>
 */

#ifndef __DT_BINDINGS_CLOCK_ENSEMBLE_H
#define __DT_BINDINGS_CLOCK_ENSEMBLE_H

#define ENSEMBLE_CLK_DUMMY			0
#define ENSEMBLE_CLK_LFRC			1
#define ENSEMBLE_CLK_LFXO			2
#define ENSEMBLE_CLK_HFRC			3
#define ENSEMBLE_CLK_HFXO			4
#define ENSEMBLE_CLK_SYST_PCLK			5
#define ENSEMBLE_CLK_UART0_SEL			6
#define ENSEMBLE_CLK_UART1_SEL			7
#define ENSEMBLE_CLK_UART2_SEL			8
#define ENSEMBLE_CLK_UART3_SEL			9
#define ENSEMBLE_CLK_UART4_SEL			10
#define ENSEMBLE_CLK_UART5_SEL			11
#define ENSEMBLE_CLK_UART6_SEL			12
#define ENSEMBLE_CLK_UART7_SEL			13
#define ENSEMBLE_CLK_UART0_EN			14
#define ENSEMBLE_CLK_UART1_EN			15
#define ENSEMBLE_CLK_UART2_EN			16
#define ENSEMBLE_CLK_UART3_EN			17
#define ENSEMBLE_CLK_UART4_EN			18
#define ENSEMBLE_CLK_UART5_EN			19
#define ENSEMBLE_CLK_UART6_EN			20
#define ENSEMBLE_CLK_UART7_EN			21
#define ENSEMBLE_CLK_CANFD_SEL			22
#define ENSEMBLE_CLK_CANFD_EN			23
#define ENSEMBLE_CLK_I2S0_SEL			24
#define ENSEMBLE_CLK_I2S1_SEL			25
#define ENSEMBLE_CLK_I2S2_SEL			26
#define ENSEMBLE_CLK_I2S3_SEL			27
#define ENSEMBLE_CLK_I2S0_EN			28
#define ENSEMBLE_CLK_I2S1_EN			29
#define ENSEMBLE_CLK_I2S2_EN			30
#define ENSEMBLE_CLK_I2S3_EN			31
#define ENSEMBLE_CLK_I3C_EN			32
#define ENSEMBLE_CLK_ADC24_EN			33
#define ENSEMBLE_CLK_ADC120_EN			34
#define ENSEMBLE_CLK_ADC121_EN			35
#define ENSEMBLE_CLK_ADC122_EN			36
#define ENSEMBLE_CLK_DAC120_EN			37
#define ENSEMBLE_CLK_DAC121_EN			38
#define ENSEMBLE_CLK_CMP0_EN			39
#define ENSEMBLE_CLK_CMP1_EN			40
#define ENSEMBLE_CLK_CMP2_EN			41
#define ENSEMBLE_CLK_CMP3_EN			42

#define ENSEMBLE_CLK_END			256

#endif /* __DT_BINDINGS_CLOCK_ENSEMBLE_H */
